In [26]:
import geopandas as gpd

In [27]:
charging_stations = gpd.read_file(r'../Data/ev_charging_units.geojson')
charging_stations.head(3)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,...,EV J1772 Power Output (kW),EV CCS Connector Count,EV CCS Power Output (kW),EV CHAdeMO Connector Count,EV CHAdeMO Power Output (kW),EV J3400 Connector Count,EV J3400 Power Output (kW),EV J3271 Connector Count,EV J3271 Power Output (kW),geometry
0,ELEC,"Aberdeen, WA - Tesla Supercharger",416 Wishkah Street,,Aberdeen,WA,98520,,877-798-3752,E,...,,0,,0,,1,150.0,0,,POINT (-123.81348 46.97668)
1,ELEC,"Aberdeen, WA - Tesla Supercharger",416 Wishkah Street,,Aberdeen,WA,98520,,877-798-3752,E,...,,0,,0,,1,150.0,0,,POINT (-123.81348 46.97668)
2,ELEC,"Aberdeen, WA - Tesla Supercharger",416 Wishkah Street,,Aberdeen,WA,98520,,877-798-3752,E,...,,0,,0,,1,150.0,0,,POINT (-123.81348 46.97668)

In [33]:
cleaned = charging_stations[['City', 'Station Name', 'EV J3400 Power Output (kW)', 'EV J3400 Connector Count', 'geometry']]
cleaned

,City,Station Name,EV J3400 Power Output (kW),EV J3400 Connector Count,geometry
0,Aberdeen,"Aberdeen, WA - Tesla Supercharger",150.0,1,POINT (-123.81348 46.97668)
1,Aberdeen,"Aberdeen, WA - Tesla Supercharger",150.0,1,POINT (-123.81348 46.97668)
2,Aberdeen,"Aberdeen, WA - Tesla Supercharger",150.0,1,POINT (-123.81348 46.97668)
3,Aberdeen,"Aberdeen, WA - Tesla Supercharger",150.0,1,POINT (-123.81348 46.97668)
4,Aberdeen,"Aberdeen, WA - Tesla Supercharger",150.0,1,POINT (-123.81348 46.97668)
...,...,...,...,...,...
1233,Auburn,Fred Meyer - Tesla Supercharger,325.0,1,POINT (-122.22411 47.31592)
1234,Auburn,Fred Meyer - Tesla Supercharger,325.0,1,POINT (-122.22411 47.31592)
1235,Auburn,Fred Meyer - Tesla Supercharger,325.0,1,POINT (-122.22411 47.31592)
1236,Auburn,Fred Meyer - Tesla Supercharger,325.0,1,POINT (-122.22411 47.31592)
1237,Auburn,Fred Meyer - Tesla Supercharger,325.0,1,POINT (-122.22411 47.31592)

In [40]:
cleaned = cleaned[cleaned['City'] == 'Seattle']
cleaned

,City,Station Name,EV J3400 Power Output (kW),EV J3400 Connector Count,geometry
223,Seattle,Thompson Seattle - Tesla Destination,,1,POINT (-122.34126 47.61034)
224,Seattle,Hotel 1000 - Tesla Destination,,1,POINT (-122.33619 47.6049)
225,Seattle,Hotel 1000 - Tesla Destination,,1,POINT (-122.33619 47.6049)
226,Seattle,Motif Seattle - Tesla Destination,,1,POINT (-122.33518 47.61017)
227,Seattle,Motif Seattle - Tesla Destination,,1,POINT (-122.33518 47.61017)
...,...,...,...,...,...
1163,Seattle,Northway West Office Building - Tesla Supercha...,,1,POINT (-122.33357 47.70695)
1164,Seattle,Northway West Office Building - Tesla Supercha...,,1,POINT (-122.33357 47.70695)
1165,Seattle,Northway West Office Building - Tesla Supercha...,,1,POINT (-122.33357 47.70695)
1166,Seattle,Northway West Office Building - Tesla Supercha...,,1,POINT (-122.33357 47.70695)
1167,Seattle,Northway West Office Building - Tesla Supercha...,,1,POINT (-122.33357 47.70695)

In [48]:
import pandas as pd

cleaned['EV J3400 Connector Count'] = pd.to_numeric(
    cleaned['EV J3400 Connector Count'], errors='coerce'
)

In [51]:
grouped = (
    cleaned.groupby('Station Name', as_index=False)
    .agg({
        'EV J3400 Connector Count': 'sum',
        'City': 'first',
        'geometry': 'first'
        
    })
)
grouped

,Station Name,EV J3400 Connector Count,City,geometry
0,2+U - Tesla Supercharger,4,Seattle,POINT (-122.3375 47.6066)
1,400 Fairview - Tesla Destination,3,Seattle,POINT (-122.33391 47.62254)
2,AGC of Washington - Tesla Destination,6,Seattle,POINT (-122.33959 47.63001)
3,Ballard Blocks - Tesla Supercharger,8,Seattle,POINT (-122.37504 47.66255)
4,Bedrooms & More - Tesla Destination,2,Seattle,POINT (-122.32491 47.66152)
5,Cedarbrook Lodge - Tesla Destination,1,Seattle,POINT (-122.28762 47.43731)
6,Fairmont Olympic Hotel - Seattle - Tesla Desti...,7,Seattle,POINT (-122.33403 47.6082)
7,Four Points by Sheraton Downtown Seattle Cente...,2,Seattle,POINT (-122.3446 47.62538)
8,Four Seasons Hotel Seattle - Tesla Destination,2,Seattle,POINT (-122.33942 47.60765)
9,Fred Meyer - Tesla Supercharger,12,Seattle,POINT (-122.3704 47.66115)
10,Hampton Inn and Suites Seattle-Downtown - Tesl...,2,Seattle,POINT (-122.34689 47.62568)
11,Homewood Suites by Hilton Seattle Downtown - T...,3,Seattle,POINT (-122.35918 47.62056)
12,Hotel 1000 - Tesla Destination,2,Seattle,POINT (-122.33619 47.6049)
13,Hotel Max - Tesla Destination,1,Seattle,POINT (-122.33636 47.61414)
14,Hotel Theodore - Tesla Destination,3,Seattle,POINT (-122.33417 47.61235)
15,Millennium Tower - Tesla Destination,6,Seattle,POINT (-122.33159 47.59919)
16,Motif Seattle - Tesla Destination,2,Seattle,POINT (-122.33518 47.61017)
17,Northgate Mall - Tesla Supercharger,16,Seattle,POINT (-122.32778 47.70659)
18,Northway West Office Building - Tesla Supercha...,12,Seattle,POINT (-122.33357 47.70695)
19,Puget Sound Solar - Tesla Destination,6,Seattle,POINT (-122.31168 47.59542)
20,Rainier Square - Level E - Tesla Destination,12,Seattle,POINT (-122.33534 47.60919)
21,Residence Inn by Marriott Seattle University D...,2,Seattle,POINT (-122.31542 47.66187)
22,Seattle Marriott Waterfront - Tesla Destination,2,Seattle,POINT (-122.34726 47.61084)
23,"Seattle, WA - Fairview Avenue North (Floor 1) ...",6,Seattle,POINT (-122.33318 47.62614)
24,"Seattle, WA - Union Street (Wall Connector) - ...",5,Seattle,POINT (-122.33189 47.61014)
25,Shafer Baillie Mansion Bed & Breakfast - Tesla...,1,Seattle,POINT (-122.31496 47.62705)
26,Thompson Seattle - Tesla Destination,1,Seattle,POINT (-122.34126 47.61034)
27,Union Square - Tesla Supercharger,10,Seattle,POINT (-122.33208 47.61002)
28,Washington Athletic Club Garage - Tesla Destin...,4,Seattle,POINT (-122.33313 47.60963)

In [55]:
grouped = gpd.GeoDataFrame(grouped, geometry='geometry', crs=cleaned.crs)
grouped.to_file("grouped_ev_stations.geojson", driver="GeoJSON")